"""v7 grouped, source-verified units; no extra model stage or source owner."""
from dataclasses import asdict
import hashlib

from . import grounded_formation as gf
from .body_payload import BODY_VERSION, FORMATION_BODY_VERSION, seal_body, validate_body
from .models import SourceProvenance

F1_BODY_PROMPT = """F1: Rewrite the supplied bounded dialogue directly into topic-local memory blocks.
Return strict JSON only: {"blocks":[{"units":[{"text":str,"origin_turn_id":str,"source_turn_ids":[str]}]}]}.
At most 16 blocks, 8 units per block, 96 units total; each text at most 2000 characters.
Blocks group one local topic, not unrelated subjects merely adjacent in time. Each unit must be independently understandable with its qualifications IN THAT SAME UNIT. Preserve scope, negation, permission, unanswered status, proposals versus acceptance, reports versus execution, changes and later reversals. Do not split a claim from a qualification that changes its meaning. Do not summarize away those boundaries. Do not infer personality, enduring rules, causality, or completion.
origin_turn_id is the actual turn making the statement, proposal, refusal, acceptance or report, not an earlier contextual turn. source_turn_ids must explicitly include its origin and ALL context needed to support every clause; use only actual supplied IDs. Units in each block follow origin source order. Do not use future statements to support an earlier origin; later corrections remain separately attributed later units. Keep uncertain reference uncertain, do not guess names or merge namesakes.
The program prefixes text with User stated: or Lumina stated: using the origin's actual role before F2. Do not write this prefix yourself. Either speaker may discuss the other. Their speech is not external execution proof. Do not invent user acceptance from assistant claims, silence or questions. Write in the source language.
No titles, transitions, summaries, graph fields or extra prose. Only the units will form the body after independent verification; grouping is not new evidence. Return an empty blocks list if nothing merits memory."""

F2_BODY_SUFFIX = """
For this v7 protocol candidates are grouped units. The groups table records original order only, NOT evidence or an authorization to borrow sources. Each supported unit must be self-contained: do not approve an unconditional claim if its indispensable qualifier occurs only in another candidate. Reject or mark insufficient the ENTIRE affected unit, even when the neighbouring qualifier might also be accepted. A unit must remain faithful if every other unit is omitted. Check local-topic grouping and source order: reject a unit whose placement falsely joins unrelated topics or implies a source-unsupported sequence. Do not use future sources to authorize an earlier statement. Rejected/insufficient text will not appear; its original slot becomes a gap. No new text may be generated by verification."""


def parse_body_f1(raw, segment):
    from .reliable_formation import _sources
    if (not isinstance(raw, dict) or set(raw) != {"blocks"} or not isinstance(raw["blocks"], list)
            or len(raw["blocks"]) > 16):
        raise gf.FormationError("body_f1_output_invalid")
    sources = _sources(segment); order = list(sources); facts, groups, issues = [], [], []
    count = 0
    for bi, block in enumerate(raw["blocks"]):
        if not isinstance(block, dict) or set(block) != {"units"} or not isinstance(block["units"], list) or not 1 <= len(block["units"]) <= 8:
            raise gf.FormationError("body_f1_group_invalid")
        group = []; last_origin = -1
        for pos, item in enumerate(block["units"]):
            index = count; count += 1
            if count > 96:
                raise gf.FormationError("body_f1_output_invalid")
            valid = isinstance(item, dict) and set(item) == {"text", "origin_turn_id", "source_turn_ids"}
            if valid:
                text, origin, ids = item["text"], item["origin_turn_id"], item["source_turn_ids"]
                valid = (isinstance(text, str) and bool(text.strip()) and len(text) <= 2000
                         and isinstance(origin, str) and origin in sources and isinstance(ids, list) and bool(ids)
                         and all(isinstance(t, str) and t in sources for t in ids)
                         and len(set(ids)) == len(ids) and origin in ids)
            if valid:
                oi = order.index(origin)
                valid = oi >= last_origin and all(order.index(t) <= oi for t in ids)
            if not valid:
                issues.append({"index": index, "code": "body_unit_source_or_order_invalid", "status": "pending"})
                group.append(None)
                continue
            last_origin = oi
            prefix = "User stated: " if sources[origin]["role"] == "user" else "Lumina stated: "
            fid = "f" + str(index)
            facts.append({"fact_id": fid, "text": prefix + text.strip(), "origin_turn_id": origin,
                          "allowed_source_ids": [tid for tid in order if tid in ids],
                          "body_position": bi, "unit_position": pos})
            group.append(fid)
        groups.append(group)
    return {"facts": facts, "groups": groups, "issues": issues}, {"facts": len(facts), "blocks": len(groups), "pending": len(issues)}


def body_payloads(segment, f1, f2, progress):
    from ._reliable_projection import reliable_unit_id
    from .reliable_formation import digest
    turns = {t.turn_id: t for t in segment.turns}
    facts = {f["fact_id"]: f for f in f1["facts"]}
    decisions = {d["fact_id"]: d for d in f2}
    receipts = {s: {k: progress["stages"][s][k] for k in ("request_digest", "response_digest", "parsed_digest", "execution")} for s in ("F1", "F2")}
    bodies, references = [], {}
    for bi, group in enumerate(f1["groups"]):
        slots = []
        for pos, fid in enumerate(group):
            status = decisions[fid]["verdict"] if fid is not None else "invalid"
            slot = {"position": pos, "status": status}
            if status == "supported":
                fact = facts[fid]; origin = turns[fact["origin_turn_id"]]
                uid = reliable_unit_id(segment, fact, version=FORMATION_BODY_VERSION)
                provenance = SourceProvenance(segment.segment_id, segment.conversation_id, origin.turn_id, origin.role,
                    origin.timestamp.isoformat(), origin.source_timezone, FORMATION_BODY_VERSION, origin.timezone_source)
                slot.update(unit_id=uid, text=fact["text"], provenance=asdict(provenance),
                    used_source_ids=decisions[fid]["used_source_ids"], source_refs=[{
                        "turn_id": tid, "source_role": turns[tid].role, "source_timestamp": turns[tid].timestamp.isoformat(),
                        "source_timezone": turns[tid].source_timezone, "source_digest": hashlib.sha256(turns[tid].content.encode()).hexdigest()
                    } for tid in fact["allowed_source_ids"]])
            slots.append(slot)
        if not any(s["status"] == "supported" for s in slots):
            continue
        body = validate_body(seal_body({"version": BODY_VERSION, "formation_version": FORMATION_BODY_VERSION,
            "source_digest": gf._entity_source_digest(segment), "segment_id": segment.segment_id,
            "conversation_id": segment.conversation_id, "block_position": bi, "slots": slots,
            "complete": all(s["status"] == "supported" for s in slots), "receipts": receipts}))
        bodies.append(body)
        for slot in slots:
            if slot["status"] == "supported":
                references[slot["unit_id"]] = {"body_ref": body["body_ref"], "body_digest": body["body_digest"], "body_unit_ref": slot["unit_id"]}
    manifest = {"references": references, "digest": digest(bodies)}
    return bodies, manifest
